# Generated by Django 6.0.4 on 2026-06-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('barber', 'Barber/Hair Stylist'), ('salon', 'Hair Salon'), ('admin', 'Admin')], db_index=True, default='client', max_length=20),
        ),
    ]
